
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu 16.04 LTS 64 bit VirtualBox (Bento)
    config.vm.box = "bento/ubuntu-16.04"
    # config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-16.04"

    config.vm.synced_folder "../_shared/", "/home/progetto/_shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "jenkins", che prevede: 
    # - Docker 
    # - Java, Gradle, Maven (no)
    # -Jenkins
    config.vm.define "jenkins" do |node|
        node.vm.hostname = "jenkins"    
        node.vm.network "private_network", ip: "10.11.1.121", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
			v.cpus = 2
#			v.cpus = 4
#            v.memory = 2048 
            v.memory = 4096 
#            v.memory = 8192 
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
 
		# 8080 -> 8081 per evitare conflitti sulla porta 8080 con altre vm  
        node.vm.network "forwarded_port", guest: 8080, host: 8081, id: 'http', auto_correct: true

        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, :inline => 'apt-get install unzip'

        node.vm.provision :shell, path: "../_shared/scripts/setup-java.sh"
        # node.vm.provision :shell, path: "../_shared/scripts/setup-gradle.sh"
        # node.vm.provision :shell, path: "../_shared/scripts/setup-maven.sh"

		# installa docker 
        node.vm.provision :shell, path: "../_shared/scripts/setup-docker.sh"
        #installa e avvia jenkins
        node.vm.provision :shell, path: "../_shared/scripts/setup-jenkins.sh"

        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo jenkins completa'"

    end

end
